---
require:
- rubocop/require_tools
- rubocop-performance
- rubocop-rspec
- rubocop-rake
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Include:
  - "**/*.rb"
  - "**/*file"
  - "**/*.gemspec"
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
  - "**/lib/assets/MatchfileTemplate"
  - "**/spec/fixtures/broken_files/broken_file.rb"
  - "**/*.provisionprofile"
Lint/ErbNewArguments:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/MultipleComparison:
  Enabled: true
Style/PercentLiteralDelimiters:
  Enabled: true
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/FrozenStringLiteralComment:
  Enabled: true
Style/SafeNavigation:
  Enabled: true
Performance/RegexpMatch:
  Enabled: true
Performance/StringReplacement:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Metrics/BlockLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']
Metrics/ModuleLength:
  Enabled: true
Naming/VariableNumber:
  Enabled: true
Style/MissingRespondToMissing:
  Enabled: true
Style/MultilineBlockChain:
  Enabled: true
Style/NumericLiteralPrefix:
  Enabled: true
Style/TernaryParentheses:
  Enabled: true
Style/EmptyMethod:
  Enabled: true
Lint/UselessAssignment:
  Exclude:
  - "**/spec/**/*"
Require/MissingRequireStatement:
  Exclude:
  - "**/spec/**/*.rb"
  - "**/spec_helper.rb"
  - spaceship/lib/spaceship/babosa_fix.rb
  - fastlane_core/lib/fastlane_core/ui/disable_colors.rb
  - "**/Fastfile"
  - "**/*.gemspec"
  - rakelib/**/*
  - "**/*.rake"
  - "**/Rakefile"
  - fastlane/**/*
  - supply/**/*
Layout/FirstHashElementIndentation:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
Layout/DotPosition:
  Enabled: true
Style/DoubleNegation:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Layout/HeredocIndentation:
  Enabled: true
Style/MixinGrouping:
  Exclude:
  - "**/spec/**/*"
Lint/SuppressedException:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Enabled: true
Style/GlobalVars:
  Enabled: true
Style/ClassAndModuleChildren:
  Enabled: true
Style/SpecialGlobalVars:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Style/WordArray:
  MinSize: 19
Style/SignalException:
  Enabled: true
Style/RedundantReturn:
  Enabled: true
Style/IfUnlessModifier:
  Enabled: true
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Metrics/ClassLength:
  Max: 320
Layout/LineLength:
  Max: 370
Metrics/ParameterLists:
  Max: 17
Style/GuardClause:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/ConditionalAssignment:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/ParenthesesAsGroupedExpression:
  Exclude:
  - "**/spec/**/*"
Naming/PredicateName:
  Enabled: false
Style/PerlBackrefs:
  Enabled: true
Layout/SpaceAroundOperators:
  Exclude:
  - "**/spec/actions_specs/xcodebuild_spec.rb"
Naming/FileName:
  Exclude:
  - "**/Dangerfile"
  - "**/Brewfile"
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Deliverfile"
  - "**/Snapfile"
  - "**/Pluginfile"
  - "**/*.gemspec"
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
Style/IfInsideElse:
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowedMethods:
  - require
  - require_relative
  - fastlane_require
  - gem
  - program
  - command
  - raise
  - attr_accessor
  - attr_reader
  - desc
  - lane
  - private_lane
  - platform
  - to
  - not_to
  - describe
  - it
  - be
  - context
  - before
  - after
Bundler/OrderedGems:
  Enabled: true
  TreatCommentsAsGroupSeparators: false
Gemspec/DevelopmentDependencies:
  Enabled: true
  EnforcedStyle: Gemfile
RSpec/ExampleLength:
  Enabled: false

